### ISSUE TITLE
[ENHANCEMENT] Expanded neume selection + visual clarity improvements

### ISSUE THREAD

**Issue by LeSniffa** [danielgarthur/neanes#21]
I have noticed that one of your previous projects called "SBMuFL" contains some glyphs that are not included in this scorewriter. That includes glyphs from all categories such as; a lot of quantity characters that aren't used often, the yfen and endofonon from the quality characters, the koronis, as well as secondary versions of the gorgon that can be used on neumes that can accept two of them. I do not know how much time it would take to import these characters to this project, but I would like to see them added since they would open up more possibilities on what would be possible on the program. 
Also I have discovered that some characters tend to overlap when placed on the same neume. For example
![image](https://user-images.githubusercontent.com/110656129/191596998-e066659b-eb43-4f7a-92f9-02478f799dfe.png) ![image](https://user-images.githubusercontent.com/110656129/191597070-d849bd99-d1ad-451c-b570-23f78b32fed4.png) ![image](https://user-images.githubusercontent.com/110656129/191597141-e737f200-614c-4633-83dc-962fa5f77e3f.png)
This can often make it difficult for the reader to tell some characters apart. Again I am not sure how good the solution that I'm suggesting is, but I think a way of editing the position of these characters to some degree will effectively erase the problem, since that feature already exists for neumes.

**Comment by danielgarthur** [comment]
Regarding neume collisions: I've added a dialog to allow users to position each supporting neume. See the docs [here](https://danielgarthur.github.io/neanes/guide/advanced.html#fine-tuning-neume-positions). 

For the secondary gorgons, these available by clicking and holding the oligon + yporroe + kentimata in the neume selector. Multiple options should show up. 
<img width="48" alt="image" src="https://user-images.githubusercontent.com/4132779/196007632-691b2232-baa5-41f4-93ff-4fc5516c7974.png">
You can then add a gorgon over the kentimata by using the normal gorgon buttons. If this isn't what you meant, please clarify. Are there other base neumes that can take secondary gorgons? If so, let me know and I can look into adding them.

Regarding the less commonly-used characters, I will try to add them soon. Some are easy, like the quantitative characters. But some, like the koronis, take longer because they require positioning information.

**Comment by LeSniffa** [comment]
Thank you for the additions. As far as I know there aren't any more neumes that can take secondary gorgons. If I happen to notice any more of them I'll be sure to update the issue.

**Comment by LeSniffa** [comment]
After looking at a few books, I've realized that in the neume bellow there is some times a digorgon or trigorgon placed above the apostrofos.
![image](https://user-images.githubusercontent.com/110656129/196128877-2399fcb7-acdf-454c-b335-16d6c9160fb5.png)

**Comment by danielgarthur** [comment]
For reference, page 604 of John's Anastasimatarion contains such a combination. I will add a way to choose these neumes, similar to the yporroe + kentimata over the oligon.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/4132779/197352087-3c5c9d41-88d1-4f47-8973-84b70003626a.png">

**Comment by danielgarthur** [comment]
I noticed that in the picture in the previous post, a gorgon may also appear above the ison of an ison + kentimata over an oligon.

**Comment by danielgarthur** [comment]
Closing this since most of it is done. I think the remaining requests are part of #23, so they will be tracked there.
