### ISSUE TITLE
Psiphiston not stretched

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#227]
### Expected result

**Note:** This is the _actual_ result with Papa Ephraim's macros.

![stretch-expected](https://github.com/danielgarthur/neanes/assets/29850/4bee4f09-32f5-4747-8139-fad1b2ba430c)

### Actual result

![stretch-actual](https://github.com/danielgarthur/neanes/assets/29850/7a39bf73-8176-4ac5-aca0-7881dc4474c0)

### Note

Same applies to other combinations.

**Comment by danielgarthur** [comment]
The code in the original macro is on line 3824 of `EzMacros.bas`. It looks like that one psifiston is scaled to 125%. I think the best course of action would be to scale the original glyph in FontForge and make it an official alternate glyph so that it can be used like a normal character anywhere without having to scale. Then the OpenType font should be able to do a contextual substitution to replace it automatically, similar to how the antikenoma is replaced for narrow characters automatically.
