### ISSUE TITLE
Classic legetos intervals are incorrect

### ISSUE THREAD

**Issue by basil** [danielgarthur/neanes#305]
I tried playing my legetos Axion Estin with "Classic Legetos" checked and was horrified at the result. I knew what classic legetos was even before listening to the sample by Fr Dositheos because for years I have been listening to recordings of Stanitsas chanting the Akathist Canon this way. And of course chanters in my home country of Lebanon sometimes chant not just legetos but even regular First Mode diatonic pieces this way. In general there is disagreement on the pitch of Segâh in Eastern music. Anyway, intervals of 6-9-15 (out of 72) sound nothing like classic legetos. Perhaps you got these from some book that was using a different denominator, like 68? In any case, after detuning by about -200 cents I was able to experiment side by side with the sample by Fr Dositheos and (by ear) 8-10-12 (out of 72) or 9-9-12 (again, out of 72) were the closest I could get experimentally.

**Comment by basil** [comment]
The description in the documentation

> If checked, hymns in the fourth mode with base notes Pa or Vou will use the classic legetos scale with Vou lowered so that the interval Vou - Di is larger than a minor third.

is also misleading. Well of course Vou - Di is larger than a minor third in classic legetos because that interval in plain diatonic (20/72) is already larger than a minor third (18/72). In classic (early 20th century Constantinoplitan) legetos it's even larger than that (probably 21/72 or 22/72?).

**Comment by danielgarthur** [comment]
What you have submitted is actually much closer to what I hear. The defaults were taken from some Psaltologion post and at the time I assumed maybe I was just ignorant of some subtlety, and went with it assuming people would change it to their desired value if it sounded wrong to them. I often hear Ga flattened on descent, which perhaps puts the scale a little closer to 6-9-15, but this seems more like a temporary attraction to Vou than the actual default scale itself.

Another issue with Legetos playback is that pieces switch between the Segah and diatonic scales depending on whether the piece is focused around Pa or Vou. I think the only way to support that would be to allow users to change scales for playback manually. That is, click a neume and "use this scale". I suppose it could be detected automatically via ison in some cases.

And yet another issue is that I sometimes hear a different scale (chromatic, maybe?) when the melody descends to Ni. An approximation using Western solfege, taking Eb as Vou, would be Eb D B D Eb.

At one point I took recordings of various chanters and looked at the frequencies but I didn't not formally write up what I found. I may try that exercise again and formally write up the frequencies.

By the way, do you have any links to recordings of Segah with the first mode? I like "classic" legetos very much and would like to hear how it sounds in the first mode.

And lastly, I am horrible at naming things. Is "classic" really the best thing to call it? I chose that because I generally associate that with older chanters, but maybe Segah is a better term? I have heard it called that as well. I don't know what is correct, and I've never seen reference to this scale in theory books.

**Comment by basil** [comment]
Regarding to the descent to Ni, I think this is just Pa being attracted upward (sharpened) to Vou (e.g. in the troparia of the 4th Mode Beatitudes) in the same way that Ga is attracted upward (sharpened) to Di in some contexts. This Pa attraction can even happen in the rare situations where a legetos piece reaches high Vou' (e.g. the Axion Estin by Arvanitis). For an example in first mode see [here](http://graeca.mrezha.net/upload/MontrealPsaltiki/Arab/ArchbishopSamuelDavid_Axion_ModeProtos.ra). I think "classic" is a fine term. This is simply a case where the diatonic scale has evolved toward a more Western set of intervals over the past century, particularly in Greece. Recordings of older chanters like Fr Dositheos (who was born in Asia Minor) provide a glimpse of earlier practice. Segâh is just the term for legetos in the Ottoman system.
