### ISSUE TITLE
Mode Key addition: heptaphonic plagal second

### ISSUE THREAD

**Issue by LeSniffa** [danielgarthur/neanes#50]
Could it be possible to add the mode key for plagal of the second "επτάφωνος"?

![image](https://user-images.githubusercontent.com/110656129/213998257-cb5d08c5-938b-4f38-aa85-90148f4c697d.png)

**Comment by basil** [comment]
This is OK, but this is usually (since the second half of the 19th century) referred to as "Chromatic Plagal Fourth Mode" as described on [this page](https://analogion.com/site/html/DoxologyPlDChromatic.html), the most famous example being the Doxology by Kosmas of Madytos. This mode is obviously borrowed from the Ottoman Maqam Hijaz Kar.

This mode is usually written based on Ni rather than Pa with a soft chromatic fthora on high Ni as in [this score](https://analogion.com/site/images/AxionEstin-GeorgiadiPriggou-PlDChromatic.jpg). In my [Axion Estin](http://byzantinemusic.org/tmp/Axion%20Estin%20Pl%204%20Chromatic%20Triantaphyllus%20Georgiadis.pdf) in this mode I just used a regular Pl 4th mode key. I still think Neanes should have a real mode key based on Ni for this mode, corresponding to the most common convention in which this mode is written on Ni. [This](https://www.youtube.com/watch?v=KxgDavJl1e8) is a good example.
