### ISSUE TITLE
[ENHANCEMENT] Export as Word doc or image file

### ISSUE THREAD

**Issue by psarsama** [danielgarthur/neanes#69]
**Is your feature request related to a problem? Please describe.**
Putting together a service packet; would be convenient to be able to embed the output of neanes into the word doc rather than exporting word doc as PDF and combining multiple PDFs.

**Describe the solution you'd like**
Ideally, export as a word doc with the neumes as images (or whatever else works) within the word doc. This would allow the user to also move things around for formatting.

**Describe alternatives you've considered**
Export the score as a high quality PNG or something that I could place onto the Word (or other software) page.

**Comment by danielgarthur** [comment]
Added export to PNG in `0.3.0-beta.14`.

Notes:

- It's recommended that you choose a high DPI resolution in order to get a clear picture when printing to paper. The default has been set to 300 DPI, which is probably good enough for most cases.
- The image export process is slow, so if you have a lot of pages, it might take a few seconds.

I spent a while trying to look into exporting directly to Word, but I couldn't find an adequate solution. Things I investigated:

- Exporting the neumes directly into Word as a font. Word justifies text using some unknown algorithm, so getting the neumes to line up the same way as in Neanes seemed impossible.
- Exporting the neumes directly into Word as a font, but into text box form elements. This kind of worked, but was really slow and would not be practical for large files because a text box was needed for each neume. Word was not intended to be used in that way.
- Use a Microsoft Office Add-in to render the file somehow. The Word API for this didn't seem like it supported rendering whatever you want.

**Comment by danielgarthur** [comment]
Reopening because this currently only works if the font is installed on the users computer.

Need to investigate how to fix this. Probably need to embed the font in the app as a data URL when exporting as PNG.

It currently works while developing locally because in that case the export library uses `http://localhost` to load the font, but when built as an electron app it uses the `app://` protocol which is not supported by the `fetch` method.

**Comment by basil** [comment]
It has been about a decade since I used Microsoft Word, but last I remember it was not an option for serious typesetting of liturgical texts and music. Ten years ago, the decent options were Adobe InDesign, QuarkXPress, and the various TeX variants. The key requirements for me are:

- Full OpenType support, including ligatures and true-drawn small capitals
- Margin kerning (e.g. hanging punctuation) as in e.g. the [`microtype` LaTeX package](https://ctan.math.illinois.edu/macros/latex/contrib/microtype/microtype.pdf)
- A decent justification algorithm (e.g., the Adobe Paragraph Composer or Knuth-Plass line breaking)
- Full EPS support

Regarding the last of these, take a look at https://basilcrow.com/Paraklesis-Common.pdf which I typeset in 2009 in Adobe InDesign. The Western notation portions were typeset in Finale, exported as EPS files, and placed as vector graphics in Adobe InDesign. This works very well for a professional level of typesetting quality.

**Comment by danielgarthur** [comment]
> Reopening because this currently only works if the font is installed on the users computer.

Fixed in `0.3.0-beta.19`.
