### ISSUE TITLE
[Enhancement] Better UI for placing gorgons on combined neumes

### ISSUE THREAD

**Issue by TugleaCristian01** [danielgarthur/neanes#79]
**This bug was found in**

- [x] Desktop

**Describe the bug**
There is a specific combination of signs that can't be introduced in a musical sheet.

**To Reproduce**
If you try to make an ison holding a Hyporrhoe and a Kendimata, both with a Gorgon on top, you can't. I think this is correct for all combinations of two supported signs, because you can only add one gorgon per "Neuma", and if you need two, it can't be made.

**Expected behavior**
It would be great to develop a solution that enables introducing two gorgons if you need so.

**Screenshots or files**
Screenshot atached.
![Bug sheet](https://user-images.githubusercontent.com/129614034/229303626-6278879b-469e-4ea7-8670-b28f5296ef2c.jpg)

**Desktop Version (please complete the following information, if applicable):**

- OS: Windows 10
- Version 0.3.0-beta.10

**Comment by danielgarthur** [comment]
This is currently possible. See this [reply](https://github.com/danielgarthur/neanes/issues/63#issuecomment-1436071209).

I think I'll keep this issue open though because it's been reported several times. This feature needs to be made easier for users to find. I'll need to think of a better UI that makes it obvious how to select multiple gorgons.

**Comment by TugleaCristian01** [comment]
Thank you!
Nevertheless, it's amazing what you did with the app and how functional and efficient it is. Great work, keep it up!

**Comment by danielgarthur** [comment]
The neume toolbar has been expanded to make it easier to select which neume a fthora, gorgon, or accidental affects. See comments on #85.
